### ISSUE TITLE
关于uploadFile上传html文件

### ISSUE THREAD

**Issue by Ben07** [upyun/node-upyun#10]
调用uploadFile上传html文件，上传成功了，文件也在又拍云上了。里面的数据也是正确的。返回的数据中statusCode是200，但是data是{}.求解

**Comment by yejingx** [comment]
能提供下上传参数吗？

**Comment by Ben07** [comment]
@yejingx 参数就是文档中说的参数。我选择是根据statusCode是否是200来判断有没上传成功了。

调用的接口是uploadFile
参数分别是 '/文件名','文件路径','text/html',true,回掉方法

关于new UPYUN的参数。涉及隐私，不能提供。抱歉

**Comment by yejingx** [comment]
@Ben07 uploadFile上传的文件是没有返回内容的，所以 data 为 {}。

**Comment by Ben07** [comment]
@yejingx 好的。我看到文档提到通用的返回格式，以为是有的了
