### ISSUE TITLE
上传方法返回40000003 ，需要提供bucket name ，但是初始化的时候已经提供了

### ISSUE THREAD

**Issue by LibiChai** [upyun/node-upyun#11]

**Comment by LibiChai** [comment]
var upyun = new UPYUN('xxxx', 'xxx', 'xxxx','v3', 'legacy');
        upyun.uploadFile("test.mp3", r.body,"audio/mpeg",false,{},function(err, result){
            console.log(result);
        })

**Comment by kaidiren** [comment]
upyun.uploadFile("/test.mp3"


 请在 test.mp3   前面加上 '/'

**Comment by cdll** [comment]
listDir也返回了这串err msg，bucket也是写了的，求助～
````
    var upyun= new UPYUN('xxx', 'yyy', 'zzz', 'v0', 'latest')
    upyun.listDir(
      'folderDir'
      ,(res, err)=>{
        console.log(res, err.data.files)
      }
    )
````

````
null [ { name: '{"msg":"need bucket name","code":40000003,"id":"196735c75f1df7d2270b457803aa028b"}',
    type: 'folder',
    length: undefined,
    last_modified: undefined } ]
````

**Comment by kaidiren** [comment]
目录请以 /  开头 例如 /your_dir

**Comment by yejingx** [comment]
这个 "/" sdk 里能自动加上吗？

**Comment by kaidiren** [comment]
那个只能去 https://github.com/upyun/node-sdk 这个项目里加了。可以的。

**Comment by cdll** [comment]
@kaidiren 灰常感谢，加上／欧了～🙏

**Comment by kaidiren** [comment]
https://github.com/upyun/node-sdk/pull/5

@cdll 如果嫌麻烦可以等稍后的版本更新。

**Comment by cdll** [comment]
@kaidiren  it dosent matter~
