### ISSUE TITLE
是否考虑支持流式上传？

### ISSUE THREAD

**Issue by Lanfei** [upyun/node-upyun#12]
这个模块现在实在是不够好用，听说在准备重构？请问是否有考虑支持流式上传？

现在的版本是，如果用户上传一张图片，服务端进行中转的话，服务端需要存临时文件，或者存在内存里，再进行转发，这其实是很浪费资源的，希望能够支持流式上传，祝又拍云越做越好。

**Comment by kaidiren** [comment]
http://docs.upyun.com/api/form_api/

HTTP FORM API 允许用户直接上传文件到 UPYUN，而不需要通过客户服务器进行中转。支持 HTTP 和 HTTPS 协议，您可以选择最优的方式提交请求。

**Comment by Lanfei** [comment]
@kaidiren 好的。

那么这个模块是否会考虑支持流式上传呢？

**Comment by kaidiren** [comment]
@Lanfei  推荐用 form api 的方式上传。因为  form api  是真对这种不需要服务器中转直接传到 upyun 的场景所提供的一种方式。比较灵活易用了。没必要再去额外做一种了。传统的rest上传方式需要在请求头附加签名，处理起来会很不方便。所以暂时不考虑支持。但是新的sdk 会集成 form api的 上传方式，欢迎关注。

**Comment by Lanfei** [comment]
赞，FORM API 因为没有 SDK，对于想快速接入的项目来说还是比较麻烦，新的 SDK 大概什么时候会发布？

**Comment by kaidiren** [comment]
争取月中吧。最近事情比较多。万一跳票了请不要见怪。_(:з」∠)_

**Comment by Lanfei** [comment]
干巴爹ToT

**Comment by Lanfei** [comment]
@kaidiren 月中了😝

**Comment by kaidiren** [comment]
可怕的温馨提示。_(:з」∠)_

**Comment by kaidiren** [comment]
https://github.com/upyun/node-sdk/commit/9d62e942e39f6fcfd3edaa5a39383384602c2667

转移到这里了。可以尝试新的版本，欢迎反馈。

**Comment by Lanfei** [comment]
@kaidiren 赞~
