### ISSUE TITLE
上传的文件包含中文字符，打开外链地址查看出现乱码。

### ISSUE THREAD

**Issue by Luncher** [upyun/node-upyun#4]
原始文件内容：
{
    "type": "ui-button",
    "name": "ui-button1-general",
    "w": 200,
    "h": 69,
    "x": 151,
    "y": 164,
    "text": "你好",
    "vTextAlign": "middle",

上传之后在浏览器打开查看：
{
    "type": "ui-button",
    "name": "ui-button1-general",
    "w": 200,
    "h": 69,
    "x": 151,
    "y": 164,
    "text": "浣犲ソ",
    "vTextAlign": "middle",

btw:
外链地址：http://lcbucket1.b0.upaiyun.com/filex1.txt
上传文件：Content-Type: 'text/plain'
checksum： true

希望帮忙看看，谢谢：）

**Comment by lisposter** [comment]
好的，我看下

**Comment by lisposter** [comment]
@Luncher 文件上传是没有问题的，sdk 并不会对编码做任何处理，即又拍云上存的文件是和你本地一样的，至于你访问是乱码，是因为你的浏览器可能设置了与你的文件不同的编码方式，例如：文件是 GBK，而浏览器默认是 UTF-8 亦或相反，你可以试试调整浏览器编码方式来看看文件内容是否正确，或者，直接下载回来对比。

**Comment by Luncher** [comment]
感谢你的回复，我后面查到了是由于中文环境下，浏览器默认编码GBK。
但是，我不能去修改每个用户的默认编码，只能改自己的文件编码。
ps:sdk能不能支持直接上传stream

**Comment by lisposter** [comment]
@Luncher 我们 sdk 只会实现基本的一些常态服务，如果你需要做编码转换，可以在你的程序中引入 iconv-lite 之类的库，转换完后再调用 sdk 上传。

目前还未支持 stream 直接 pipe 进来，但是 sdk 内部是使用 stream 形式去上传的（如果你是指定了一个本地路径的话）

**Comment by sabakugaara** [comment]
新项目地址：https://github.com/upyun/node-sdk 欢迎使用
